### ISSUE TITLE
Text Metadata Update Endpoint

### ISSUE THREAD

**Issue by jeffkinnison** [tesserae/apitess#33]
To update text metadata, I think we only need an endpoint that accepts the metadata. Do you think we need to include the file upload as well? I'm thinking that should be isolated to ingest.

This could be a POST request to the /texts/<object_id> endpoint. Since the operation should be quick, we probably don't need status updates.

**Comment by nOkuda** [comment]
Here's what I had originally planned for text metadata updating: https://tess-new.caset.buffalo.edu/docs/api/endpoints/texts-objid/#patch.

I agree that it would be best to separate ingestion from metadata updating. Maybe we should prevent users from changing `path` in the metadata. If a user really wants to reingest, they could DELETE the text and then re-POST it.

**Comment by nOkuda** [comment]
I ended up prohibiting update of `path` and `divisions` on the Text entities. (#37)
