### ISSUE TITLE
Add Pagination to /parallels/

### ISSUE THREAD

**Issue by jeffkinnison** [tesserae/apitess#40]
When retrieving cached results, /parallels/ returns the entire results set. Because this occurs in a single request, the frontend cannot display search status and it looks like the application is idle.

Request to add pagination with the same parameters as in /parallels/xxxxxx/ to /parallels/ when retrieving cached results.

**Comment by nOkuda** [comment]
I ended up qualifying the redirect URL with pagination information in #42. I think it would have been more pure to let API users catch the 303 Redirect and tack on their own pagination parameters, but I also think that it would be nicer to the API users to fetch only 100 matches in case they didn't understand the full implications of following the 303.
