### ISSUE TITLE
Multitext Matches Have Odd Tags

### ISSUE THREAD

**Issue by jeffkinnison** [tesserae/apitess#61]
Multitext results seem to be packaged with incorrect locus tag information. When looking at entries in cross-ref.units, the tag provided for each unit is a single number instead of an `<author>.<title> <locus>` tag. I've combed through the REST API and v5 multitext code but don't see an obvious source for this.

View of the in-memory multitext result object:

![image](https://user-images.githubusercontent.com/3553147/97194859-03fc0480-1781-11eb-83c4-009479a191b6.png)

View of the displayed data:

![image](https://user-images.githubusercontent.com/3553147/97194626-bf706900-1780-11eb-8b3e-9991ebe14c80.png)

**Comment by nOkuda** [comment]
I've updated the backend code to provide more information in cross-ref.units.tag. Those changes are also now up on olivia.
